# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 312bd909518eda9bc8670ba7f68acc641aa70936244b5f8e3bc68b439c5ff353429cf79353fd3cc8cf875f7bf33ce55f6a69b41a6edc2b8d04422a0589ef0ce6

test:
  secret_key_base: 1e4e88371dfe059a81a63fddb365e9c03a2d92a3829d590050887c9072fac3409f9f66172c7964d0068b8e9a1a4e120a5fb15f2285b6faf5a0e0590a571e9ac6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
